[project]
org-name = "ballerina"
version = "0.6.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "socket"
    version = "0.6.0"
    path = "./lib/ballerina-socket-0.6.0-java.jar"
    groupId = "ballerina"
    modules = ["socket"]
